import React from "react";

export default function PartyForm({ formState, handleFormChange, formSubmit }) {
  return (
    <div>
      <form id="partyForm" onSubmit={formSubmit}>
        <div>
          <input
            type="text"
            id="name"
            name="name"
            value={formState.name}
            onChange={handleFormChange}
            required
          />
        </div>
        <div>
          <input
            type="date"
            id="dateInviteSent"
            name="dateInviteSent"
            onChange={handleFormChange}
            value={formState.dateInviteSent}
          />
        </div>
        <div>
          <input
            type="date"
            id="dateRSVPReceived"
            name="dateRSVPReceived"
            onChange={handleFormChange}
            value={formState.dateRSVPReceived}
          />
        </div>
        <div>
          <input
            type="text"
            id="street1"
            name="street1"
            value={formState.street1}
            onChange={handleFormChange}
          />
        </div>
        <div>
          <input
            type="text"
            id="street2"
            name="street2"
            value={formState.street2}
            onChange={handleFormChange}
          />
        </div>
        <div>
          <input
            type="text"
            id="city"
            name="city"
            value={formState.city}
            onChange={handleFormChange}
          />
        </div>
        <div>
          <input
            type="text"
            id="state"
            name="state"
            value={formState.state}
            onChange={handleFormChange}
          />
        </div>
        <div>
          <input
            type="text"
            id="zipcode"
            name="zipcode"
            value={formState.zipcode}
            onChange={handleFormChange}
          />
        </div>
        <div>
          <input
            type="text"
            id="country"
            name="country"
            value={formState.country}
            onChange={handleFormChange}
          />
        </div>
        <div className="flex items-center justify-center p-6 rounded-b">
          <button
            type="submit"
            className="p-1 rounded-lg hover:scale-105 hover:text-white bg-sky-300 dark:bg-blue-700 drop-shadow-xl"
          >
            Save
          </button>
        </div>
      </form>
    </div>
  );
}
